# Generated by Django 2.1.5 on 2019-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='REQUIRES ATTENTION', max_length=20, verbose_name='Status/Статус'),
        ),
    ]
