# Generated by Django 2.1.5 on 2019-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('N', 'Not confirmed'), ('R', 'Requires attention'), ('W', 'Work in progress'), ('C', 'Completed')], default='N', max_length=1, verbose_name='Status/Статус'),
        ),
    ]
